# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

export EDITOR=/usr/local/bin/nvim

# variables setting powerlevel9k prompt
precmd() { print "" }
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=" ❯ "
DEFAULT_USER="Matt"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_middle
POWERLEVEL9K_RBENV_BACKGROUND="red"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="white"
POWERLEVEL9K_VI_INSERT_MODE_STRING=""
POWERLEVEL9K_VI_COMMAND_MODE_STRING="CMD Mode"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="8"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="magenta"
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="8"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode history)

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pl9kfork/powerlevel9k"

# Make oh-my-zsh upgrades purely a manual operation
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true




#
# Paths
#

typeset -gU cdpath fpath mailpath path

# # Set the list of directories that Zsh searches for programs.
 path=(
    /Users/Matt/bin
    $path
   )

# Set the the list of directories that cd searches.
cdpath=(
  /Users/Matt/bin
  /Users/Matt/Projects
  $cdpath
)


########################
# Set up ubiquitous tmux
########################
_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running

# Plugins to be loaded (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git bundler brew gem heroku thefuck rbenv pyenv sublime vi-mode)

######
# Less
######

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# Load the oh-my-zsh customizations
source $ZSH/oh-my-zsh.sh

# Add bulk renaming with zmv
autoload -U zmv

# Automatically list directory contents upon cd
function chpwd() {
    emulate -L zsh
    ls -a
}

# Enable cd without typing cd
setopt auto_cd

# Open files with quicklook using ql alias
function ql() {
    qlmanage -p "$1" >& /dev/null &
}

# Jump to the root of project in git repository
function groot() {
    cd `git root`
}

alias tmux="TERM=screen-256color-bce tmux"
alias rake="noglob bundled_rake"
alias gcom="git commit -m"
alias zshconf="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"

# RBENV/PYENV Initialization

if [[ -z $TMUX ]]; then
 if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
fi

# DIRENV Initialization
eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
